// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'capture-guide': string;
  'guides': string;
  'horizontal-line': string;
  'mask': string;
  'vertical-line': string;
}
export const cssExports: CssExports;
export default cssExports;
